title: Dianne Johnson
logo: /assets/img/photo-14.jpg
#logo: /assets/img/headshot_circle.png
description:  Contact Me
linkedin: "https://www.linkedin.com/in/diannejohnsondataanalyst/"
email: "DianneJohnson.DataAnalyst@gmail.com"

github_link: false
#show_downloads: false
theme: jekyll-theme-minimal
